### ISSUE TITLE
Leverage TwoLevelCache for resiliency

### ISSUE THREAD

**Issue by luisdavim** [zx80/cachetools-utils#2]
TwoLevelCache might not have a significant impact on latency in most cases but it would have on resiliency.
For example if we have a TwoLevelCache setup with the first level as a local in memory cache and the second layer using Redis or Memcached the cache could have a flag to ignore failures on the second level, so as long as the first level is available the app would remain functional.

This should probably be false by default and when set to true it would still log some warning, or maybe it can throw some custom exception that can be handled by the app and the developer can decide to ignore it or not.

**Comment by zx80** [comment]
Interesting point! This suggest to build in some resiliency when accessing the second level.

**Comment by zx80** [comment]
I have added a `resilient` option to `TwoLevelCache`.
Now it does just that: ignoring second level errors, however this does not mean recovering, eg by reconnecting to the second level cache if appropriate.
